### ISSUE TITLE
New icon for locations

### ISSUE THREAD

**Issue by Tomlennon21** [nice-digital/nice-design-system#125]
The addition of a location icon into the design system. This is to be used firstly on the events page to mark various locations that the events may be held at.

https://www.nice.org.uk/news/events

**Comment by ediblecode** [comment]
@Tomlennon21 are you thinking a standard pin drop type icon? @wa-rren-dev this would be easy enough to add into nice-icons?

**Comment by Tomlennon21** [comment]
Hi, yes just a standard location icon please

**Comment by wa-rren-dev** [comment]
Yep, will make a card for it :)

**Comment by ediblecode** [comment]
Changes to icons does me think that #81 would be useful to do sooner rather than later

**Comment by ediblecode** [comment]
Closed by #164

**Comment by ediblecode** [comment]
@Tomlennon21 this will be released this week
