### ISSUE TITLE
Has panel--inverse been implemented? The style isn't appearing on either Beta or Live.

### ISSUE THREAD

**Issue by TrishB70** [nice-digital/nice-design-system#156]

**Comment by wa-rren-dev** [comment]
So there's a `panel--impact` which is similar? We possibly have a slight deviation in our naming which we can address.

If you go to https://design-system.nice.org.uk/storybook/?path=/story/panel--try-it-out and click on "knobs" (I know) then you can test the three current variants via the select list.

**Comment by wa-rren-dev** [comment]
![image](https://user-images.githubusercontent.com/6341474/109792667-a9315880-7c0b-11eb-93ed-86dce04441da.png)

**Comment by TrishB70** [comment]
Impact is perfect. Actually better.

**Comment by wa-rren-dev** [comment]
Also I notice it's not the standard teal background, it's one of the other ones. _I_ think we should have a standard `inverse` style as well so let me know if you agree and I'll put it in the backlog.

**Comment by TrishB70** [comment]
A standard inverse would be useful. And the background of --impact should ideally be the same as for the Hero container: #18646e? It looks odd currently (#517489).

**Comment by ediblecode** [comment]
Possibly v1 removed `--inverse` which might be a regression. We did do some rationalisation on panels to get the 3:

- default (grey, used for supporting info)
- impact which is teal(ish) background
- and primary which is white background and teal(ish) thick border

Looks like `--inverse` was in v0 (see https://nice-digital.github.io/nice-design-system/components/panel/#default-light-panel) but not sure what happened to it. Also not sure its use-case over the other panels: maybe it's just for asthetic purposes? If we can articulate a clear use-case for an inverse then I'm all for it as a 4th panel type. Hope that helps?

**Comment by ediblecode** [comment]
> the background of --impact should ideally be the same as for the Hero container:

I think it's actually _deliberately_ different to avoid teal overload!

**Comment by TrishB70** [comment]
Yes there was mention of Teal overload! But having an off-teal colour doesn't really work either. To my eye it looks odd. The two teals are clashing. That's the designer in me. --inverse was a very dark grey which worked.

**Comment by ediblecode** [comment]
> But having an off-teal colour doesn't really work either. To my eye it looks odd. The two teals are clashing.

sounds like that's something to look at too then.

> But `--inverse` was a very dark grey which worked

cool let's re-add this in then
