### ISSUE TITLE
Increased spacing between list items

### ISSUE THREAD

**Issue by wa-rren-dev** [nice-digital/nice-design-system#173]
As discussed here https://github.com/nice-digital/nice-design-system/discussions/141
In Jira at https://nicedigital.atlassian.net/browse/NDS-153

**Comment by wa-rren-dev** [comment]
@rnickr let's stick any further implementation discussion in here

**Comment by wa-rren-dev** [comment]
So @ediblecode @TrishB70 @rnickr ... 

There's already a modifier...!

`<ul class="list list--loose">
<li>Hello</li>
<li>There</li>
</ul>`

Shall I add another modifier?

`<ul class="list list--looser">
<li>Hello</li>
<li>There</li>
</ul>`

**Comment by TrishB70** [comment]
Is it, in fact, any looser?

**Comment by rnickr** [comment]
yeah it's twice as loose

**Comment by TrishB70** [comment]
I would. Well actually I'd just change loose to .5 but that's a personal preference thing and so therefore verboten.

**Comment by rnickr** [comment]
Just seems easier if we have this as default though doesn't it? Rather than having to add the class every time?

**Comment by TrishB70** [comment]
.5 is peachy keen.

**Comment by wa-rren-dev** [comment]
On investigation it's probably best to do in modifiers if we can just from a backwards compatibility point of view. As Ian pointed out in the other thread, there are lists in _all_ the components, so if we made it default we'd need to go through an zero out a fair amount of margins. It's certainly doable but not as quick as doing it with a modifier.

**Comment by TrishB70** [comment]
Good point.

**Comment by rnickr** [comment]
Would we need to add the modifiers in manually or can we automate that?

**Comment by wa-rren-dev** [comment]
That may just be laziness to be honest. Would be interested in @ediblecode 's opinion. I fight my idleness daily.

**Comment by wa-rren-dev** [comment]
> Would we need to add the modifiers in manually or can we automate that?

What do you want the moon on a stick?

**Comment by TrishB70** [comment]
Is that an option?

**Comment by rnickr** [comment]
oh you got one of those as well!!!

**Comment by rnickr** [comment]
basically just checking how we get it on CKS, Guidance, things like that where we can't go in and amend every page.

**Comment by wa-rren-dev** [comment]
> basically just checking how we get it on CKS, Guidance, things like that where we can't go in and amend every page.

Yeah maybe we do need it in by default. Can either of you imagine anywhere where it could break anything we wouldn't think of? We'd test all the components individually but is there anywhere a list might be used out of place at all? I know it's a very open question.

A global tag-level style change would need a little bit of a regression test. Would be good to get into some basic visual regression testing across key pages for this sort of thing.

**Comment by rnickr** [comment]
I see why we've never done this before now. 

It should be mostly nav elements like menus that use lists other than standard bullet lists in content i think.

There's the timeline which is list markup as well, example here: https://www.nice.org.uk/about/what-we-do/life-sciences/scientific-advice/express-scientific-advice

**Comment by wa-rren-dev** [comment]
So what I've done is given the new default `ul`, `ol` or `.list` a margin-bottom of `0.25rem`. The `.list--loose` modifier is now `0.5rem` and there's a new `.list--tight` modifier for zeroing out the margins. You can see a demo on the docs and on storybook.

https://test-design-system.nice.org.uk/foundations/lists/

https://test-design-system.nice.org.uk/storybook/?path=/story/typography-lists--default

Welcome to raise any other discussions if you think other options might be necessary!
