### ISSUE TITLE
Tabs component not stacking in mobile 

### ISSUE THREAD

**Issue by Tomlennon21** [nice-digital/nice-design-system#190]
The new tabs component seems to not be stacking correctly when viewed in mobile. 
![tabs](https://user-images.githubusercontent.com/78083583/114556202-60d07600-9c60-11eb-87d8-50fe6a5ade3b.jpg)

**Comment by wa-rren-dev** [comment]
@Tomlennon21 So in the interim we're going to go with this

![image](https://user-images.githubusercontent.com/6341474/114844890-25a28400-9dd3-11eb-9ea9-0b2fe483f6aa.png)

until we make further decisions around what we should do on mobile.

Hoping to get this out this week 🤞

**Comment by Tomlennon21** [comment]
Thanks Warren.
