### ISSUE TITLE
Update peer dependencies for React

### ISSUE THREAD

**Issue by ediblecode** [nice-digital/nice-design-system#196]
Each component references React as a peer dep, for example:

https://github.com/nice-digital/nice-design-system/blob/fee3ac08e81cd85f727d03c8a09335502096f16b/components/nds-panel/package.json#L40

However, React 17 still works, but you get lots of warnings:

![image](https://user-images.githubusercontent.com/893676/115076570-a6a56c80-9ef4-11eb-8c76-c54a26e1c779.png)

So we should update the compatible React versions in peer deps

**Comment by ediblecode** [comment]
I think the version could be `^16 || ^17`. Also, might be worth adding react-dom as a peer dep too?

**Comment by wa-rren-dev** [comment]
https://github.com/nice-digital/nice-design-system/pull/218
