### ISSUE TITLE
Support NextJS link component

### ISSUE THREAD

**Issue by ediblecode** [nice-digital/nice-design-system#213]
We have somponents that allow passing a prop of `elementType` to customise the component used to render the link. An example is horizontal nav, but there are definitely others (probably breadcrumb and stacked nav and maybe more). 

See: https://github.com/nice-digital/nice-design-system/blob/748033b4a526bb2d19264b2c28fa48350fb8e598/components/nds-horizontal-nav/src/HorizontalNav.js#L28-L32

This logic (assuming an `a` tag needs an href prop, otherwise use `to`) works for normal anchors and `Link` components from Gatsby/Reach router and React router. However, [links in NextJS](https://nextjs.org/docs/api-reference/next/link) use the `href` prop instead of `to` so you get errors lik:

> Error: Failed prop type: The prop `href` expects a `string` or `object` in `<Link>`, but got `undefined` instead.

**Comment by wa-rren-dev** [comment]
will be resolved in https://github.com/nice-digital/nice-design-system/pull/218
