### ISSUE TITLE
Option to show card metadata label

### ISSUE THREAD

**Issue by ediblecode** [nice-digital/nice-design-system#214]
Card metadata sometimes have visible labels, and sometimes the label is visually hidden as the value gives enough context on its own. For example:
![image](https://user-images.githubusercontent.com/893676/120035038-de282e00-bff5-11eb-8c25-bc1b07613c58.png)
The date needs a visible label but the other 2 don't

**Comment by wa-rren-dev** [comment]
@ediblecode something like this okay you think? no styling on the label? 
![image](https://user-images.githubusercontent.com/6341474/125492004-05b2ab6a-cb64-4b75-a019-a61561cde5ce.png)

**Comment by ediblecode** [comment]
Was closed in #218
