### ISSUE TITLE
Committee advert template converting to NDS

### ISSUE THREAD

**Issue by Tomlennon21** [nice-digital/nice-design-system#217]
Hi,
currently when creating committee adverts in orchard we use the "Join a committee page" template. This is currently in bootstrap only. Are we able to convert this over so that the adverts are created in the NDS? 

I think this was raised previously but nothing has been mentioned since.

**Comment by wa-rren-dev** [comment]
Hi Tom, could you send a link through to the join a committee template page and I'll take a look?

**Comment by Tomlennon21** [comment]
Here is the link to the template we use. As you can see there is no option to drop into the niceorg client

https://www.nice.org.uk/Admin/Contents/Create/CommitteeGroup

**Comment by wa-rren-dev** [comment]
Will close this out and follow you up on teams - this is something that needs addressing on the CMS side of things
