### ISSUE TITLE
Decide what to do with the src folder

### ISSUE THREAD

**Issue by ediblecode** [nice-digital/nice-design-system#71]
We have a src folder in the v1 branch left over from v0 that contains:

- favicons/logos
- tables/results info components.

We should decide what to do with these and move them somewhere appropriate

**Comment by ediblecode** [comment]
This also begs the question of how we provide logos/favicons to be consumed by applications

**Comment by ediblecode** [comment]
The table and results info components are now packages in their own right, so can be removed.

The assets still need dealing with. Maybe we have a nds-logos package with these in?

**Comment by wa-rren-dev** [comment]
Yes i like the idea of a `nds-logos` or `nds-assets` package

**Comment by ediblecode** [comment]
Yeah be good to have SVGs for high res stuff, but also images cropped to required sizes for various different devices, like apple icons, twitter and open graph, windows 10 tiles etc
