### ISSUE TITLE
Remove print logo

### ISSUE THREAD

**Issue by ediblecode** [nice-digital/nice-design-system#76]
We have a logo that gets inserted as a before pseudo element for print:

https://github.com/nhsevidence/nice-design-system/blob/v1/packages/design-system/scss/helpers/_helpers-print.scss#L43

However, this is going to handled by the Global Nav, so this logo can be removed from the NDS SCSS. This will also reduce the bundle size, which is A Good Thing.

**Comment by ediblecode** [comment]
This is the SCSS: https://github.com/nice-digital/nice-design-system/blob/v1/components/design-system/scss/helpers/_helpers-print.scss#L41-L48

**Comment by wa-rren-dev** [comment]
this was resolved in yesteryear
