### ISSUE TITLE
Custom Props for Automated Testing Selectors

### ISSUE THREAD

**Issue by mgallagher1980** [nice-digital/nice-design-system#77]
I would like to pass in a custom prop so that i can focus on certain elements that are passed down from the design system. For example, we are importing and using the StackedNav component in IDAM and i would like to add a data selector to the link component within the stacked nav but cannot currently do so.

**Comment by wa-rren-dev** [comment]
Closing this as by default all our components pass down any additional props now. Any that don't are being retroactively amended to support this.
