### ISSUE TITLE
Fallback font showing on buttons

### ISSUE THREAD

**Issue by wa-rren-dev** [nice-digital/nice-design-system#92]
In some instances the font of buttons will be Arial where the cascaded font is another

**Comment by ediblecode** [comment]
This is because of https://github.com/necolas/normalize.css/issues/694, so upgrading to Normalize v8 will fix this. And we can do that now that we've stopped supporting old IE officially

**Comment by ediblecode** [comment]
We're using v8 of normalize now, so closing this:

https://github.com/nice-digital/nice-design-system/blob/88329347c4985509b2347ecc27daec0a33aef607/components/design-system/package.json#L70
